### ISSUE TITLE
'Security System Current State': Characteristic not in required or optional characteristic section for service Switch. 

### ISSUE THREAD

**Issue by sebastiangoldstein** [haywirecoder/homebridge-envisalink-ademco#14]
[08/09/2021, 15:37:17] [homebridge-envisalink-ademco] This plugin generated a warning from the characteristic 'Security System Current State': Characteristic not in required or optional characteristic section for service Switch. Adding anyway....

Just saw this for the first time today. Been running the plugin for over a year with no issues.

**Comment by haywirecoder** [comment]
Hi,
I believe this is associated with update with Homebridge. This is just an informative warning message, Homebridge will automatically correct the value to a valid one or ignore. It is on my todo to do a housekeeping update due to libraries being updated and functions being changed. So, this warning will disappear as part of housekeeping release. But no action is required on your part and plugin is working as design.

**Comment by haywirecoder** [comment]
Hi,

1.1.26 was just release. It correct the waring message you were receiving in the log.
