### ISSUE TITLE
Add explicit partition numbers

### ISSUE THREAD

**Issue by jaytavares** [haywirecoder/homebridge-envisalink-ademco#17]
Currently, partition numbers are inferred by their position in the `partitions` array in the plugin config. This means that you must add all partitions up to and including the partition you want to control via HomeKit. 

It would be helpful if we could add an optional `number` field to the partition object to allow configuration like this:

```jsonc

"partitions": [
                {
                    "name": "3rd Floor",
                    "number": 4
                }
            ],
```

Instead of:

```jsonc

"partitions": [
                {
                    "name": "Common"
                },
                {
                    "name": "1st Floor"
                },
                {
                    "name": "2nd Floor"
                },
                {
                    "name": "3rd Floor"
                }
            ],
```

In the above example, I only want HomeKit control of the 3rd floor partition. Currently, I'm forced to also add the Common, 1st Floor, and 2nd Floor partitions to HomeKit in order to add the 3rd Floor partition. This adds clutter to HomeKit with unneeded accessories. It also means that the home-wide security system status requires all partitions to be armed in order to show as armed, for example.

**Comment by haywirecoder** [comment]
Hi,

I don't have a multiple partition configuration, so I have no way of testing the final outcome. I added new optional field called "partitionNumber". Please confirm it is working before I add the options in the official build and UI configuration file.  Just replace index.js with the  posted version in GitHub. 
Example

"partitions": [
                {
                    "name": "3rd Floor",
                    "partitionNumber": 4
                }
            ],

**Comment by jaytavares** [comment]
Tested. That works on my setup. 👍

One thing I've noticed though is that Homebridge is not receiving the partition status change update in response to a request to arm/disarm from within HomeKit.  I'm guessing it might have something to do with my multi-partition setup (I've got a Honeywell Vista 128-FBPT panel with 5 of the 8 total partitions configured). I haven't been able to pinpoint the exact cause just yet though. I'm going to file a separate issue to track that.

Thanks for your quick response!

**Comment by haywirecoder** [comment]
Hi,

Looked over the code again,  its seem their a few spots that also need to modify based on adding this option.  I will post once those changes are made and you can test.  I believe all the changes will be contained in the index.js.

**Comment by jaytavares** [comment]
Awesome. Thanks a lot!

**Comment by haywirecoder** [comment]
Hi, 
Posted an updated index.js which should correct the partition update.

**Comment by jaytavares** [comment]
I'm seeing the following error message:
```
TypeError: Cannot read property 'processingAlarm' of undefined
    at EnvisalinkPlatform.systemUpdate (/usr/local/lib/node_modules/homebridge-envisalink-ademco/index.js:191:24)
    at EnvisaLink.emit (events.js:400:28)
    at updateKeypad (/usr/local/lib/node_modules/homebridge-envisalink-ademco/envisalink.js:478:15)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-envisalink-ademco/envisalink.js:137:23)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by haywirecoder** [comment]
Hi, 
Posted another index.js with enhance error trapping.  I believe what occurred is the plug-in got an update from a non registered partition (which will happened since we can skip partitions now) and wasn't able to process the data. I fix the code so it check to assure that it is a register partition before it process the updates and simply ignore the rest.

I have also made few other changes, since you indicated your using 128 panel, which this plug-in wasn't original written to support, base on the document there are some minor items how to send bypass commands. 

To active the new section of code change the deviceType field in Configuration file
 "deviceType": "128FBP",

The new config.schema.json has also been posted to manage the partition and devices type using the UI.

**Comment by jaytavares** [comment]
Thanks for that. I installed and tested it. It looks like the partition updates are working following commands, so that's great. There might be something else going on though since shortly after disarming my partition HomeKit reports the security system as being armed￼ again.

**Comment by haywirecoder** [comment]
Hmm...
1. Does Homekit clear arm state and few sec later go back to arm and later disarm again? If this is the case the command timeout value (commandTimeOut) is too short. The log file should also give a warning that this has occurred.
2. Are any of the other partition armed?

**Comment by jaytavares** [comment]
1. It displays the correct arm state shortly after arming/disarming. (Presumably from the partition status change message.) Shortly after, the status changes. This is an improvement over what it used to do, which was just sit there saying "arming..." or "disarming...". 

2. I believe it switches to reporting the armed state of partition 1, in my case, our common area. Perhaps it is reading the state from the virtual keypad updates? I do see some logs about "partition 1" which it shouldn't be monitoring.

**Comment by haywirecoder** [comment]
Hi,
1. I posted another Index.js tonight, its cleanup and optimization coding so don't believe it will correct the issue. But at least we will be running the same code base. 
2.  The best course of action is turn on debug in Homebridge (under Homebridge setting in UI)  and provide the output when you arm and disarm. In debug it will provide the raw output from Envisakit module and updates. With raw output hopefully will be able determine why you are getting another update.  Please indicate which partition you want to be monitoring in Homekit.

**Comment by jaytavares** [comment]
Hey there, sorry for the late reply. I did some troubleshooting and discovered that the [`Envisalink.partitions` property](https://github.com/haywirecoder/homebridge-envisalink-ademco/blob/ab21119555af275f7d804fbff1f101bd36dbf033/envisalink.js#L23) is what is causing my alarm system status in HomeKit (which should only be the 3rd partition) to show the status of the common (1st) partition.

The checks on lines [247](https://github.com/haywirecoder/homebridge-envisalink-ademco/blob/ab21119555af275f7d804fbff1f101bd36dbf033/envisalink.js#L247) and [460](https://github.com/haywirecoder/homebridge-envisalink-ademco/blob/ab21119555af275f7d804fbff1f101bd36dbf033/envisalink.js#L460) are ignoring any messages re: partitions > 1. So, I set `panelpartition` in my config manually to 3. Now I see:

```
[22/11/2021, 23:25:38] [Envisalink-Ademco] Command | %00,03,1C08,32,00,****DISARMED****  READY TO ARM  $,00,03,1C08,32,00,****DISARMED****  READY TO ARM   | Acknowledged
[22/11/2021, 23:25:38] [Envisalink-Ademco] System status changed to:  READY
[22/11/2021, 23:25:38] [Envisalink-Ademco] Command | %00,05,8C08,21,00,OFFC ARMED STAY1  ZONE BYPASSED $,00,05,8C08,21,00,OFFC ARMED STAY1  ZONE BYPASSED  | Acknowledged

**I armed the common partition (1) here ---->**

[22/11/2021, 23:25:39] [Envisalink-Ademco] Partition Change | %02,0401010304000000$,02,0401010304000000 | has been detected.
[22/11/2021, 23:25:39] [Envisalink-Ademco] Partition status changed to:  ARMED_STAY

**Plugin set my alarm status to the status of partition 1 (I'm guessing there is a missing check of the `partitionNumber` config setting somewhere) ---->**

[22/11/2021, 23:25:39] [Envisalink-Ademco] Set system status on accessory 3rd Floor to ARMED_STAY

[22/11/2021, 23:25:39] [Envisalink-Ademco] Getting status. ARMED_STAY
[22/11/2021, 23:25:39] [Envisalink-Ademco] Partition status changed to:  READY
[22/11/2021, 23:25:39] [Envisalink-Ademco] Partition status changed to:  READY
[22/11/2021, 23:25:39] [Envisalink-Ademco] Command | %00,01,8C08,21,03,****DISARMED****  READY TO ARM  $,00,01,8C08,21,03,****DISARMED****  READY TO ARM   | Acknowledged
[22/11/2021, 23:25:39] [Envisalink-Ademco] System status changed to:  ARMED_STAY
[22/11/2021, 23:25:40] [Envisalink-Ademco] Command | %00,02,1C08,05,00,****DISARMED****  READY TO ARM  $,00,02,1C08,05,00,****DISARMED****  READY TO ARM   | Acknowledged
[22/11/2021, 23:25:40] [Envisalink-Ademco] System status changed to:  READY
```

After the system status was set to ARMED_STAY, my alarm system shows as "OFF"; however, it also displays a message indicating that it is "Disarming...":

<img width="543" alt="Screen Shot 2021-11-22 at 11 35 33 PM" src="https://user-images.githubusercontent.com/711127/142972081-60308f5c-79da-498a-81e4-696126e691e7.png">

This message just stays there until I quit the Home app and restart it. The state of my partition hasn't changed at all through out this--it is still just off; however, upon restarting, my status is now shown as "HOME" (the status of the Common (1) partition):
<img width="527" alt="Screen Shot 2021-11-22 at 11 40 54 PM" src="https://user-images.githubusercontent.com/711127/142972231-cdb77b8c-ce7c-41b7-899a-62c86e19022b.png">

**Comment by haywirecoder** [comment]
Hi,
Looking over the section of logging, it wasn't what was there -- but absence of log data. It seem there is a hold over attribute when I initial created this module that was never removed from the core engine. It could be root of these issues with update since that attribute was the definition for the number of partitions and default to 1 and suppress some other non primary update from the Envisalink device.  I have removed the attribute from the core engine. Here are the step to update. This time you will need to replace Envisalink.js and index.js file with one I have posted. You should now see more events being generated with the debug.
Do the following test and provide the output (if they fail)
1. From keypad arm any partition other than the one being monitored. (Nothing should happened to monitored partition).
2. Disarm from the keypad any partition other than the one being monitored.  (Nothing should happened to monitored partition).
3.  From keypad arm the one being monitored. (Monitored partition should change).
4. From Keypad disarm the one being monitored. (Monitored partition should change).
5. From Homekit Arm and Disarm (Monitored partition should change).

I am also making assumption that Envisalink module is already configure to access all partition. 

Please note, was working few new features so we may see battery status now and other detail in HomeKit. Still testing those...so they can be ignored for now.
