### ISSUE TITLE
Night mode constantly "Arming" in HomeKit

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#22]
I'm really grateful all the work you've put into this plugin.

When I arm the alarm via Home or Away, the feedback in the upper left corner of the HomeKit screen says "Arming" and then the red light appears along with the current state: "Home or Away". 

When I arm via "Night" -> "Arming" appears for a split second, then "Night" appears and then it goes back to "Arming". The system is armed and it will disarm when I select "Off". I didn't think it was a worth mentioning, but then I had a false alarm this morning and went to the alarm screen to find the button in the "Off" position. Not sure if this behavior is liked tot he false Arm or not.

**Comment by haywirecoder** [comment]
Hi,

Night setting is truly dependent on your alarm panel configuration. The plug-in send the command for night (e.g. <pin>33), however what the panel returns will dictate what actual mode is reflected on home kit. I did notice that it does take long for "alarming" to clear when I use the night mode. 

When alarm triggered it should indicate "Alarm", are you indicating that Home didn't send a notification of triggered event? What were your actions after you got false alarm? In general just as night mode the plug-in just read the event coming from panel via Envisalink board. I would need a debug log to see, why HomeKit does't triggered alert event, if you alarm is sounding.

**Comment by 7RDR7** [comment]
It is my understanding from Envisalink that their API does not support "Night" mode. Although "Night" is supported by their web app, it is not supported via the API, and they have little interest in fixing the shortcoming.

**Comment by haywirecoder** [comment]
Hi @7RDR7,

It is really depends on how your panel was programmed and this maybe something that should be clarify in the readme. 

1.  This plug-in uses the virtual keypad, when a user request night-stay it sends a <pin>33, which is the default code command to request Night-stay. This something anyone can test and confirm on a physical panel and see if goes the night-stay. If it doesn't than the plug-in would not know the correct command code to get to Night-Stay. An enhancement can be made to allow the user to override the default code command, but I would need to know if this really an issue worth investing time.

2. The plug-in will read from EVL partition change of  "Code 6 - Arm-Instant (Zero Delay-Stay)". This is normally map to Night-Mode. However, you are correct this actually could  be configured differently on the panel. Thus, resulting in another state, thus the plug-in will report something different than "Night". The best test is manually enable Night-Mode on the physical keypad and see what state the plug-in reports. If Night-Mode is NOT configured for Zero-Delay-Stay, the plug-in will simple report Stay (e.g. Home), since Envisalink doesn't return any other code.
