### ISSUE TITLE
Did bypassEnabled change to only open sensors?

### ISSUE THREAD

**Issue by HerbM3** [haywirecoder/homebridge-envisalink-ademco#38]
A while back I was using bypassEnabled to disable a motion sensor when having guests spend the night. I'd hit the bypass button in HomeKit and it bypassed the sensor. But then it stopped working at some point. I opened an issue in December and then forgot all about it. Apologies.

Now I see in the documentation, it says: "bypassEnabled : true | false - A true value allows zones to be bypass when open (faulted)" So that means If the motion sensor hasn't been tripped, then it's closed and the bypass won't work. Has it always worked this way?  Because I swear it worked for me before not being tripped.

I just bypassed the sensor via the controller panel. It shows as bypassed in HomeKit. I can undo the bypass via the HomeKit switch. But I cannot reenable it, assuming because it is not open... Am I getting this right?

**Comment by haywirecoder** [comment]
Hi,

The bypass function in the module is design to bypass a faulted zone (e.g. An upstairs windows that is left opened for venting during the spring...its has low risk but it prevents the system from arming...etc). The functionality was primary designed for  automation, which the user has to preselect the zones that can be automatically bypass.  It was not designed to bypass a zone that is not in a faulted state. However,  based on the description of your uses case it would be nice to do a bypass zone regardless of state. The tricky part is you wouldn't want a single control (button) to bypass everything with bypassEnabled ...so how best to represent this in HomeKit is the trick. 
If I understand your request ---  you want a more target method to bypass zone regardless of state (fault/no-fault) correct?

**Comment by HerbM3** [comment]
" you want a more target method to bypass zone regardless of state (fault/no-fault) correct?"

That would be fantastic! Yes, please. I do see your point about it being difficult to implement into HomeKit.

**Comment by haywirecoder** [comment]
Hi,

The code is complete, the changes are encapsulated in envisalink.js, index.js, and accessories/zoneAccessory.js. If you copy these files to your homebridge install you can try it prior to the release.  To active the new functionality you will need to disable the global bypass switch using the following

"bypass": [
                {
                    "enabledbyPass": false,
                    "quickbypass": false
                }
            ]

This will result in any zone entry with  "bypassEnabled": true to create a separate switch to bypass the zone regardless of fault state. By design (per Ademco alarm spec) zones are fire and CO zone can't be bypassed.   In addition, while you can bypass zone separately, unbypassing one zone, will unbypass all of them (the panel doesn't have a method for individual unbypass). In addition, once the alarm is disarmed all bypass zones are cleared -- Once again panel didn't provide another method. If you are aware of a code sequence on the panel all perm or individual unbypass please let me know.

**Comment by HerbM3** [comment]
Wow. You went above and beyond. Thank you. I will try to get to testing it today.

Thanks again.

**Comment by haywirecoder** [comment]
Enhancement added in update version 2.0.5

**Comment by dtpanic** [comment]
I just updated to 2.0.5 and now Homebridge fails to start with the following error:

TypeError: Cannot read properties of undefined (reading 'enabledbyPass')

I don't currently have the bypass properties in my config as they're optional.

**Comment by haywirecoder** [comment]
Correct the issue and release a new package to address the issue.

**Comment by HerbM3** [comment]
Thank you so much!On May 1, 2023, at 2:41 PM, haywirecoder ***@***.***> wrote:﻿
Enhancement added in the update version 2.0.5
