### ISSUE TITLE
PIN Integer type for Homebridge config JSON disallows some PINs

### ISSUE THREAD

**Issue by koleson** [haywirecoder/homebridge-envisalink-ademco#4]
PINs with leading 0s cannot be configured correctly because the integer type coercion will simply strip them.

For example, the PIN `0001` will simply be stored in the config as `1`; `0123` will be stored as `123`.  As a result, the plugin is unable to enter a valid PIN via the virtual keypad and the commands time out, crashing Homebridge.

It seems like instead, this should be a `"string"`.  While you lose some type checking on entry, it allows leading 0s, which is around 10% of the available PIN space. 😄 

**Workarounds:**  

- Set a PIN in the Ademco system that starts with something other than 0.
- Edit the resulting config JSON key to use a string in quotes (e.g. "0001" instead of 1)

https://github.com/haywirecoder/homebridge-envisalink-ademco/blob/b9354b831e8d84859cd6d93ebfe3097d29cf5e8f/config.schema.json#L42

**Comment by koleson** [comment]
Created #5 to address this - let me know what you think.

**Comment by haywirecoder** [comment]
Good catch. The fix is two part. 
1. Changing the JSON configuration file to type string and creating a pattern attribute to only allow digits. This will allow a PIN starting with 0 to be entered correctly.

2. The module itself needs to protect itself from incorrect formatted PIN code. This will be done on initialization of the module and if PIN is not a number the module will terminate. If the PIN is not 4 characters a warning will be given.

I made both changes and will release as part of the next update.   My only remaining question is you indicated the homebridge crash. Can you provide logs or test PIN to cause the crash, I can't reproduce the crash I just get the timeout message.

**Comment by haywirecoder** [comment]
1.1.6 release correct leading zero dropping if configured using the UX. Added routines to validated PIN length and structure in both JSON configuration file and runtime code.
