### ISSUE TITLE
Optional flag to suppress warnings?

### ISSUE THREAD

**Issue by irctrakz** [haywirecoder/homebridge-envisalink-ademco#45]
Hi, this plugin continues to be awesome / rock solid.

Wondering if it might be possible to add an optional config flag for the suppression of these messages:

`[Envisalink-Ademco] The alarm system was not ready, and a zone fault was detected. The request for state change of undefined is ignored, see the alarm system keypad for more information.`

Basically my use-case; I have a Schlage Encode Plus - Homekit enabled lock, that when a user unlocks the door (using either the internal bolt, or the external RFID / keypad) there's a routine that automatically disarms the alarm. This works fantastically well! However if the alarm is already in a disarmed state, and someone unlocks the door, the above warning is generated. 

(To close the loop on the automation, when everyone in the household leaves the home, the door automatically locks and enables the alarm - this also works very well!)

**Comment by haywirecoder** [comment]
Hi,

This is just a warning message, and shouldn't impact the automation.  I can change this message (and 1 or 2 others) to info in the next version, since this message is more informational and not as concerning as other plug warnings (e.g. command not completing timely, failure execution of command...etc). 
I shy away from adding more flags and logic such as this since it just adds more complexity to the code without adding a net functionality... just a cosmetic functionality for a non-UX.

**Comment by haywirecoder** [comment]
I noticed a minor logic error...the plug shouldn't be giving a warning (or any message) since your system has already been disarmed it...should just ignore the request silently. You shouldn't see this message in the next version if your system is going from disarm to disarm.

**Comment by irctrakz** [comment]
Yet again, you continue to impress. Thank you for the due diligence and quality of this plugin.

**Comment by irctrakz** [comment]
Any chance we can have a release with this fix? Would be an awesome Christmas pressie! ;-)

**Comment by haywirecoder** [comment]
Santa came early :-) ... The new version has been release, sorry for delay but life got in the way at time. Feel free to re-open if you are still seeing warning message in the log. The plug-in now ignore command that are request for changing of state to current state.
