### ISSUE TITLE
Homebridge Envisalink Accessories Not Showing up in Apple Home

### ISSUE THREAD

**Issue by blinkhappy** [haywirecoder/homebridge-envisalink-ademco#46]
I currently have my Ademco Vista 20P security system connected to Envisalink. My sensors are also visible and functioning in Homebridge via your plugin. Unfortunately, this accessories don’t make it to Apple Home as my other accessories have. I know that’s not a great deal of information, but if there’s something that I’m missing that you could think of, I’d really appreciate some advice. 

Thanks so much for the great plugin,
Scott

**Comment by haywirecoder** [comment]
Hi,

Based on your comment, if the sensors are in Homebridge UI, than the plug-in is functioning correctly. Remember the plug-in connected to Homebridge, its interaction is only with homebridge not Apple Home. 
What it sounds like your have an issue with between Homebridge and Home. My recommendation is either re-register the bridge in Home again or create child bridge with an unique homebridge hub QR to register. Otherwise you may have to open with issue Homebridge project to get help.
