### ISSUE TITLE
"Envisalink data steam format invalid!"

### ISSUE THREAD

**Issue by kyle-rs** [haywirecoder/homebridge-envisalink-ademco#54]
Frequently getting these errors (various sensors, no actual change...just reports this and then the incorrect status is updated through the bridge):

[Envisalink] Envisalink data steam format invalid! : '%00,01,0008,09,00,FAULT 09 HALL   WINDOW

**Comment by haywirecoder** [comment]
Hi,

The error indicates that the Envisalink module is sending data in the incorrect format. Data coming from the module should be encapsulated between % and $. The message above is missing character $ from the message, hence module sending an error since it can't determine the end of the message from the module. This will also result in the status of the sensor not being updated. This is a low-level module format, would check your Envisalink configuration and any recent changes if these are new errors.

**Comment by kyle-rs** [comment]
Thank you for replying. I opened up a support ticket with Envisalink and this was the response:

We have nothing to do with the TPI unfortunately. You should ask the developer to communicate directly with their contact at Envisacor

**Comment by kyle-rs** [comment]
Currently using an ADT prom on a Vista 20P...will swap that out for a non ADT one this weekend and see if that perhaps fixes the issue.
