### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.

### ISSUE THREAD

**Issue by AdamHLG** [haywirecoder/homebridge-envisalink-ademco#8]
I am trying to install this plugin on my Homebridge.   After I confirmed and set the IP address of my Envisalink module and set the password, I restart Homebridge and Homebridge crashes while trying to start.  Taking a look at the logs I get the following error:

0|homebridge  | [10/29/2020, 4:29:22 PM] [Envisalink-Ademco] Initializing Envisalink-Ademco platform...
0|homebridge  | [10/29/2020, 4:29:22 PM] [Envisalink-Ademco] Configuring Envisalink Ademco platform.
0|homebridge  | [10/29/2020, 4:29:22 PM] [Envisalink-Ademco] Unhandled accessory type: undefined
0|homebridge  | [10/29/2020, 4:29:22 PM] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
0|homebridge  |     at EnvisalinkAccessory.Accessory [as constructor] (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:235:11)
0|homebridge  |     at new EnvisalinkAccessory (/usr/lib/node_modules/homebridge-envisalink-ademco/index.js:261:19)
0|homebridge  |     at new EnvisalinkPlatform (/usr/lib/node_modules/homebridge-envisalink-ademco/index.js:103:33)
0|homebridge  |     at /usr/lib/node_modules/homebridge/src/server.ts:395:40
0|homebridge  |     at Array.forEach (<anonymous>)
0|homebridge  |     at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
0|homebridge  |     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:151:29)
0|homebridge  |     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
0|homebridge  |     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:985:32)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
0|homebridge  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
0|homebridge  | [10/29/2020, 4:29:22 PM] Got SIGTERM, shutting down Homebridge...

I have searched high and low on the Internet and the only information and feedback I can find is that folks are using this plugin and it works. I cannot figure out why it is not working for me.  I am fairly certain the Envisalink module is working properly.

I am not a programmer but know enough to ask for help!

Any clue you can offer?  Thanks.

**Comment by haywirecoder** [comment]
Hi,
From this error, 
0|homebridge | [10/29/2020, 4:29:22 PM] [Envisalink-Ademco] Unhandled accessory type: undefined

You seem to have defined an accessory type that is unknown or blank in your config.json file. Look at the "sensorType" attribute and make sure it matches a valid type  motion, window, door, leak, or smoke. Each Zone device must contain a name and sensortype.

**Comment by AdamHLG** [comment]
Do you mean 'undefined' in the specific section of the config.json file applicable to Envisalink-Ademco?  My config.json is fine using the backup config.json without the new language for Envisalink-Ademco.   

Below is the section for EnvisaLink-Ademco with sensitive information marked out by "x".  I have one partition for this alarm and have not added zones yet because I at least wanted to get this running before adding zones.  I have 56 non-consecutive zones and that is a lot of typing of information into the config.json file if its going to keep crashing on startup.  I thought I saw that entering Zones was optional at least in the beginning until I see if I can get Homebridge to start correctly with this plugin.  Am I wrong?  I did try entering a single zone for the front door as a test but that did not work either.     

{
            "name": "Envisalink-Ademco",
            "host": "10.xxx.xxx.xxx",
            "port": 4025,
            "deviceType": "Honeywell Vista",
            "password": "xxxx",
            "pin": "xxxx",
            "openZoneTimeout": 30,
            "heartbeatInterval": 30,
            "commandTimeOut": 10,
            "autoreconnect": true,
            "partitions": [
                {
                    "name": "House"
                }
            ],
            "zones": [
                {
                    "bypassEnabled": false
                }
            ],
            "bypass": [
                {
                    "quickbypass": false
                }
            ],
            "platform": "Envisalink-Ademco"
        }

If there is a version of the above syntax you want me to try I can give it a go; otherwise, I have no other leads to pursue to try and get this to work.

Thanks.

**Comment by haywirecoder** [comment]
Hi,

Your configuration file is incorrect.  Based on your configuration you don't any zones to monitor and you don't wish to have bypass button enabled. So your configuration should be:

{
"name": "Envisalink-Ademco",
"host": "10.xxx.xxx.xxx",
"port": 4025,
"deviceType": "Honeywell Vista",
"password": "xxxx",
"pin": "xxxx",
"openZoneTimeout": 30,
"heartbeatInterval": 30,
"commandTimeOut": 10,
"autoreconnect": true,
"partitions": [
{
"name": "House"
}
],
"platform": "Envisalink-Ademco"
}

When an attributes is optional it shouldn't be present in the configuration file. For configuration block such as zone, the plug-in expect at-least one zone defined since the section is present in configuration file. Since there is nothing define this an error and process shut down. 
I would recommend you use the Homebridge UI to manage these configuration setting, it makes this process much simpler and cleaner and would prevent mis-configuration.
In the next update (v1.1.20), I will add routines to simple ignore incorrectly configured sections. This will allow module to start-up in a "default" state while ignoring configuration issues. However, simplest correction to your issue is remove the un-need section as shown above or simple define a zone and provide a bypass name for the control as shown in the readme.

**Comment by AdamHLG** [comment]
OMG – This worked!  Thank you!!!!!.

These days, I use Homebridge UI as the front end for my Raspberry Pi running Homebridge.  I think I understand everything you said.  That said, I do not understand how to fix this through the Web UI for Homebridge (I assume part of this involves what you are fixing in the update).  My first step to getting this working was to copy and paste your snippet into the Atom text editor manually, edit my individual IP and password and PIN, and then uploading the fixed config.json to my Homebridge the old-fashioned way.  This worked!!!  And I see the new Accessory in HomeKit to arm and disarm the alarm.  Progress!!

Next, I wanted to add a single Zone as a test.  Using the Homebridge UI, I simply added my front door as Zone 1 - Partition 1 (I only have 1 Partition but I do have 56 non-consecutive Zones).   Reloading the new config.json with this 1 Zone via the Homebridge Web UI crashed Homebridge again on restart for the same reasons you mentioned.  The snipped that crashed Homebridge looked like this after I added the Zone in the Homebridge Web UI:

{
            "name": "Envisalink-Ademco",
            "host": "10.xxx.xxx.xxx",
            "port": 4025,
            "deviceType": "Honeywell Vista",
            "password": "xxxx",
            "pin": "xxxx",
            "openZoneTimeout": 30,
            "heartbeatInterval": 30,
            "commandTimeOut": 10,
            "autoreconnect": true,
            "sessionwatcher": true,
            "partitions": [
                {
                    "name": "House"
                }
            ],
            "zones": [
                {
                    "name": "Front Door",
                    "partition": "1",
                    "zoneNumber": "1",
                    "sensorType": "door",
                    "bypassEnabled": false
                }
            ],
            "bypass": [
                {
                    "quickbypass": false
                }
            ],
            "platform": "Envisalink-Ademco"
        }

So it looks like the Homebridge UI is writing bad config for me for whatever reason – or - - I am not filling something in correctly in the settings displayed in the Homebridge UI causing this.  

Anyway, if I manually edit the config.json file in the Atom text editor to add the Zone, I did get my first test Zone to work (and work perfectly - - the front door (Zone 1) shows up in HomeKit and responds to opening and closing the door):  It looks like this:

{
            "name": "Envisalink-Ademco",
            "host": "10.xxx.xxx.xxx",
            "port": 4025,
            "deviceType": "Honeywell Vista",
            "password": "xxxx",
            "pin": "xxxx",
            "openZoneTimeout": 30,
            "heartbeatInterval": 30,
            "commandTimeOut": 10,
            "autoreconnect": true,
            "partitions": [
                {
                    "name": "House"
                }
            ],
            "zones": [
                {
                    "name": "Front Door",
                    "partition": "1",
                    "zoneNumber": "1",
                    "sensorType": "door",
                    "bypassEnabled": true
                }
            ],
            "platform": "Envisalink-Ademco"
        }
    ],

So at this point I am calling this major progress for me.  Worst case scenario is that I manually build my Zone table in the Atom text browser instead of Homebridge UI, or I see if your next release fixes the interaction with the Homebridge UI, or that I learn from you what I am setting incorrectly in the Homebridge UI to allow me to add the Zones one at a time without creating the error into the config.json that crashes Homebridge.

I should add – I am learning as I go.  Thank you for being patient.  I do not understand the difference between the lines that say “bypass": [
                {
                    "quickbypass": false
                }
And the lines within each Zone entry that says "bypassEnabled": true   .  I don’t know how this interacts with HomeKit without seeing it and trying it.   I typically do not bypass zones anyway.  I have a Home and Away where that is preprogrammed into the alarm so I assume that all remains.   

I hope the above makes sense.  Thank you for your hard work I had no pace else to turn.  This is the first GitHub ticket I ever opened and I hope this helps people that follow in my path.

To wrap this up, I guess as feedback I would say as follows:  It would be great right out of the gate in the Homebridge UI to simply enter the IP address, PIN and password and not need to enter any zones.  This would allow the end user to see if the Envisalink module connects with your plugin properly.  Once that works, it would be great to have the ability to add zones one at a time so we can test zones in HomeKit and make sure things are working.  Finally, maybe its just me but I don’t understand the difference between the config.json lines (or what is causing these settings in the Homebridge Web UI) for “bypassenabled”  and “quickbypass” and how those settings work, and I am not sure if I am making a wrong setting in the Homebridge UI or if your upcoming release will address this issue.

Anyway thank you again.  The fact I am making progress would be impossible without you.  If you want to keep this ticket open I am happy to test your next release and provide feedback.

**Comment by haywirecoder** [comment]
Hi 

I tried a few times (adding and removing home bypass entry and even zones entries) it worked without any issues with the Homebridge UI (homebridge-config-ui-x v4.31.0) plug-in setting.  By default the plug-in doesn't require any zone data and UI only require that user updating IP address and PIN. The UI defaults these values to 192.168.2.X for IP address and Pin to 1234. In addition you can simple update the config.json using the Homebridge configurator. I would confirm your are using the lastest version of homebridge and UI. Its not clear why you are getting invalidate json entries.

About the bypass functionality:

Homekit security control doesn't have the functionality for bypassing faulted zones in the security control. In order to provide this feature, this plug-in can optionally create a bypass switch. Using the following

 "bypass": [
                { 
                    "name": "<NAME OF SWITCH IN HOMEBRIDGE>",
                    "quickbypass": false
                }
            ],


The error you are receiving as noted in the previous comments is you are missing the "name" attribute.

As documented quickbypass is a panel configuration. If you set it to true the plug-in will send the "quick bypass" command to the panel. You will not have to worry about "_bypassEnabled_" setting for each zone.

If you don't have quick bypass turned-on in your panel you have to tell the plug-in that which zone can be bypass -- There are multiple reason you may not want to just press one switch to bypass all zones that are in homekit. Hence the bypassEnabled attribute in each zone entry. For example, you may not want your front door and back door bypass automatic using the switch because you want to confirm those are closed. Keep in mind to not over load the Envisalink buffer the plug sleep 500ms sec between bypass command so 50 devices would take 25sec to complete the bypass. 
 
The best way I found to quickly add multiple zone,  is set up one zone correctly and copy and paste in the homebridge config editor -- make sure you look at the format for json, change the name and zone number for each. The UI of-course can be used to avoid format issues and validate afterward.

v1.1.20 will add functionality to ignore bad configuration and notify the user it is incorrect and being ignored.

**Comment by AdamHLG** [comment]
Thanks.  The above is VERY useful.

I am using homebridge-config-ui-x v4.31.0 and I am on Homebridge 1.2.3 (I recognize this was rolled back to 1.1.6 but 1.2.3 has otherwise been working for me perfectly).  Still, when simply adding a Zone via the Settings tab on Homebridge UI, I get this inserted every time causing the error:
 
],
"bypass": [
{
"quickbypass": false
}
],

Now that I understand the issue, I can configure the config.json manually and get things to work.  I just want you to know about it.

Thanks again for your hard work and dedication.

**Comment by haywirecoder** [comment]
Hi ,

I believe I understand why the Homebridge UI is resulting in an incorrect bypass entry. I posted a new config.schema.json file which control the Homebridge UI configuration for this plug-ins.  This can simple be copied over the /homebridge-envisalink-ademco file, if you wish to test it out. 

This will be part of v1.1.20 update once, I let it run in my environment for awhile.

**Comment by haywirecoder** [comment]
Update 1.1.20 release which address main concerns and comments
